[supervisord]
nodaemon=false
logfile=./supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=./supervisord.pid
nodaemon=false
minfds=1024
minprocs=200

[program:graduation_project_backend]
command=uvicorn app.main:app --host 127.0.0.1 --port 8000 --reload
directory=%(here)s
user=user
autostart=true
autorestart=true
startsecs=1
startretries=3
restart_delay=5
stdout_logfile=./logs/backend.stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=./logs/backend.stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
environment=PYTHONUNBUFFERED=1
